site_name: NASA Astronomy Picture of the Day API Quickstart
site_url: https://codymauro.github.io/APOD-API-Test/

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.sections

nav:
  - Overview: index.md
  - Making a GET Request: request.md
  - Adding Advanced Parameters: params.md
  - Python Implementation: python.md
  - cUrl Commands: curl.md
  - Troubleshooting: troubleshoot.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_css:
  - styles/extra.css