site_name: "Understanding APIs: NASA's Astronomy Picture of the Day Quickstart"
site_url: https://codymauro.github.io/testing-NASA-API/

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.sections

nav:
  - Step 1 · Understand APIs: index.md
  - Step 2 · Get NASA Data: nasa-api.md
  - Step 3 · Set Up Postman: postman.md
  - Step 4 · Make a GET Request: request.md
  - Step 5 · Troubleshoot: troubleshoot.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_css:
  - styles/extra.css